apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dialogflow-ui-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - host: "*.ui.dialogflow.cloud.ushakov.co"
    http:
      paths:
      - path: /
        backend:
          serviceName: dialogflow-ui-service
          servicePort: http
  tls:
  - hosts:
    - '*.ui.dialogflow.cloud.ushakov.co'
    secretName: ui-cert