apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: web
spec:
  entryPoints:
    - http
    - https
  routes:
  - match: (HostRegexp(`{subdomain:.+}.web.ushaflow.io`) || HostRegexp(`{subdomain:.+}.web.ushaflow.com`) || HostRegexp(`{subdomain:.+}.ui.dialogflow.cloud.ushakov.co`)) && Method(`GET`)
    kind: Rule
    services:
    - name: web
      port: 80
  - match: HostRegexp(`{subdomain:.+}.web.ushaflow.io`) && Method(`POST`)
    kind: Rule
    services:
    - name: ssr
      port: 80
  tls:
    secretName: web-cert
